package nd.max.core.atlas

import java.io.File
import java.io.IOException
import java.nio.charset.StandardCharsets
import java.nio.file.AtomicMoveNotSupportedException
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardCopyOption

/**
 * The real store backing (`T5.5`), used by the app and by its tests.
 *
 * On a device the directory is app-private (`noBackupFilesDir/atlas`), which is deliberate: this
 * evidence is reconstructible, so it has no business in a backup, and a restored cache from another
 * device would be evidence about a machine the user no longer has. In tests the same class is pointed
 * at a temporary directory, so the shipped write path — temporary file, fsync-by-close, atomic
 * rename — is the one exercised.
 *
 * **Atomic replace is not decoration.** A cache entry that is half-written parses as far as it goes
 * and then fails, and a reader cannot tell that from a genuinely different device. Writing to a
 * temporary name and renaming means a reader always sees either the previous entry or the new one.
 * `ATOMIC_MOVE` is requested and a plain replace is the fallback, because some filesystems refuse the
 * atomic flag; the fallback is still a rename inside one directory, never a truncate-in-place.
 */
class AtlasFileStoreIo(private val directory: Path) : AtlasStoreIo {

    override fun read(name: String): String? {
        val file = pathOf(name)
        if (!Files.isRegularFile(file)) return null
        return try {
            String(Files.readAllBytes(file), StandardCharsets.UTF_8)
        } catch (_: IOException) {
            null
        } catch (_: SecurityException) {
            null
        }
    }

    override fun write(name: String, text: String): Boolean {
        val target = pathOf(name)
        return try {
            Files.createDirectories(directory)
            val temporary = directory.resolve("$name.tmp")
            Files.write(temporary, text.toByteArray(StandardCharsets.UTF_8))
            try {
                Files.move(temporary, target, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE)
            } catch (_: AtomicMoveNotSupportedException) {
                Files.move(temporary, target, StandardCopyOption.REPLACE_EXISTING)
            }
            true
        } catch (_: IOException) {
            false
        } catch (_: SecurityException) {
            false
        }
    }

    override fun delete(name: String): Boolean = try {
        Files.deleteIfExists(pathOf(name))
    } catch (_: IOException) {
        false
    } catch (_: SecurityException) {
        false
    }

    override fun list(): List<String> = try {
        if (!Files.isDirectory(directory)) {
            emptyList()
        } else {
            Files.newDirectoryStream(directory).use { stream ->
                // Sorted so a scan over the store is deterministic; a test that depends on directory
                // order is a test that fails on another filesystem.
                stream.map { it.fileName.toString() }.sorted()
            }
        }
    } catch (_: IOException) {
        emptyList()
    } catch (_: SecurityException) {
        emptyList()
    }

    private fun pathOf(name: String): Path {
        require(SAFE_NAME.matches(name)) { "a store entry name is a plain file name: $name" }
        return directory.resolve(name)
    }

    companion object {
        /** Entry names are generated by the store; anything else is refused rather than resolved. */
        private val SAFE_NAME = Regex("^[A-Za-z0-9._-]{1,120}$")

        /** The app-private directory the store lives in, relative to a context's private storage. */
        const val DIRECTORY_NAME: String = "atlas"

        /** The directory under a private files root. */
        fun directoryFor(privateRoot: File): File = File(privateRoot, DIRECTORY_NAME)
    }
}
